In [1]:
import pandas as pd 

df = pd.read_csv('medical_examination.csv')

df.head()

,id,age,sex,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

### 1) Importação de biliotecas e dos dados

In [38]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# 1
df = pd.read_csv('medical_examination.csv')

In [39]:
# 2
df['overweight'] = (df['weight'] / ((df['height'] / 100) ** 2) > 25).astype(int)

In [44]:
# 3

df['colesterol'] = (df['cholesterol'] > 1).astype(int)
df['gluc'] = (df['gluc'] > 1).astype(int)

df.head()

,id,age,sex,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,overweight,colesterol
0,0,18393,2,168,62.0,110,80,1,0,0,0,1,0,0,0
1,1,20228,1,156,85.0,140,90,3,0,0,0,1,1,1,1
2,2,18857,1,165,64.0,130,70,3,0,0,0,0,1,0,1
3,3,17623,2,169,82.0,150,100,1,0,0,0,1,1,1,0
4,4,17474,1,156,56.0,100,60,1,0,0,0,0,0,0,0

In [ ]:
# 4

def draw_cat_plot():
    sns.catplot(
        data = df,
        x = "cholesterol",
        hue = "cardio",
        kind = "count"
    )
    plt.show()

In [87]:
# 5

df_cat = pd.melt(
    df,
    id_vars=["cardio"],
    value_vars=[
        "cholesterol",
        "gluc",
        "smoke",
        "alco",
        "active",
        "overweight"
    ]
)

df_cat.head(20)

    cardio     variable  value
0        0  cholesterol      1
1        1  cholesterol      3
2        1  cholesterol      3
3        1  cholesterol      1
4        0  cholesterol      1
5        0  cholesterol      2
6        0  cholesterol      3
7        1  cholesterol      3
8        0  cholesterol      1
9        0  cholesterol      1
10       0  cholesterol      1
11       0  cholesterol      1
12       0  cholesterol      1
13       0  cholesterol      1
14       0  cholesterol      1
15       1  cholesterol      1
16       0  cholesterol      1
17       0  cholesterol      1
18       0  cholesterol      1
19       0  cholesterol      1

In [91]:
# 6 

df_cat = df_cat.rename(columns={"variable": "feature", "value": "value"})

df_cat = df_cat.groupby(["cardio", "feature", "value"]).size().reset_index(name="count")

df_cat.head(50)

    cardio      feature  value  count
0        0       active      0   6378
1        0       active      1  28643
2        0         alco      0  33080
3        0         alco      1   1941
4        0  cholesterol      1  29330
5        0  cholesterol      2   3799
6        0  cholesterol      3   1892
7        0         gluc      0  35021
8        0   overweight      0  15915
9        0   overweight      1  19106
10       0        smoke      0  31781
11       0        smoke      1   3240
12       1       active      0   7361
13       1       active      1  27618
14       1         alco      0  33156
15       1         alco      1   1823
16       1  cholesterol      1  23055
17       1  cholesterol      2   5750
18       1  cholesterol      3   6174
19       1         gluc      0  34979
20       1   overweight      0  10539
21       1   overweight      1  24440
22       1        smoke      0  32050
23       1        smoke      1   2929

In [ ]:
# 7,  8 e 9

def draw_cat_plot():
    fig = sns.catplot(
        data=df_cat,
        x="feature",
        y="count",
        hue="value",
        col="cardio",
        kind="bar"
    ).fig
    fig.savefig('catplot.png')
    return fig

In [99]:
# 10
def draw_heat_map():
    # Clean the data
    df_heat = df[
        (df['ap_lo'] <= df['ap_hi']) &
        (df['height'] >= df['height'].quantile(0.025)) &
        (df['height'] <= df['height'].quantile(0.975)) &
        (df['weight'] >= df['weight'].quantile(0.025)) &
        (df['weight'] <= df['weight'].quantile(0.975))
    ]

    # Calculate the correlation matrix
    corr = df_heat.corr()

    # Generate a mask for the upper triangle
    mask = np.triu(np.ones_like(corr, dtype=bool))

    # Set up the matplotlib figure
    fig, ax = plt.subplots(figsize=(12, 10))

    # Draw the heatmap
    sns.heatmap(
        corr,
        mask=mask,
        annot=True,
        fmt=".1f",
        center=0,
        vmax=0.3,
        vmin=-0.1,
        square=True,
        linewidths=0.5,
        cbar_kws={"shrink": 0.5}
    )

    fig.savefig('heatmap.png')
    return fig

In [ ]:
# 11
df_heat = None

In [ ]:
# 12
 corr = None

In [ ]:
# 13
 mask = None

In [ ]:
 # 14
    fig, ax = None

In [ ]:
# 15

In [ ]:
# 16
 fig.savefig('heatmap.png')
return fig

ValueError: Could not interpret value `` for `x`. Value is a string, but `data` was not passed.